fix error C4002: too many arguments for function-like macro invocation 'free' -- due to MSVC debug builds introducing a free() macro override in system's crtdbg.h